feat(auto-perms): support more persistent types and use the new common style job (#465)
**Description**
<!--
Please include a summary of the change and which issue is fixed. Please
also include relevant motivation and context. List any dependencies that
are required for this change.
-->
⚒️ Fixes  # <!--(issue)-->

**⚙️ Type of change**

- [x] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [x] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**
<!--
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details
for your test configuration
-->

**📃 Notes:**
<!-- Please enter any other relevant information here -->

**✔️ Checklist:**

- [x] ⚖️ My code follows the style guidelines of this project
- [x] 👀 I have performed a self-review of my own code
- [x] #️⃣ I have commented my code, particularly in hard-to-understand
areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is
effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic
versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the
following.

- [ ] 🪞 I have opened a PR on
[truecharts/containers](https://github.com/truecharts/containers) adding
the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called
`icon.png`

---

_Please don't blindly check all the boxes. Read them and only check
those that apply.
Those checkboxes are there for the reviewer to see what is this all
about and
the status of this PR with a quick glance._

---------

Co-authored-by: Kjeld Schouten <kjeld@schouten-lebbing.nl>

diff --git a/library/common-test/tests/addons/vpn_test.yaml b/library/common-test/tests/addons/vpn_test.yaml
--- a/library/common-test/tests/addons/vpn_test.yaml
+++ b/library/common-test/tests/addons/vpn_test.yaml
@@ -345,13 +345,52 @@ tests:
               port: 8080
     asserts:
       - hasDocuments:
-          count: 2
-      - documentIndex: &DeploymentDocument 0
+          count: 3
+      - documentIndex: &JobDocument 0
+        isKind:
+          of: Job
+      - documentIndex: &DeploymentDocument 1
         isKind:
           of: Deployment
-      - documentIndex: &ServiceDocument 1
+      - documentIndex: &ServiceDocument 2
         isKind:
           of: Service
+      - documentIndex: *JobDocument
+        equal:
+          path: metadata.name
+          value: release-name-common-test-autopermissions
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.volumes
+          content:
+            name: vpnconfig
+            hostPath:
+              path: /path/to/file
+              type: File
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.containers[0].volumeMounts
+          content:
+            name: vpnconfig
+            mountPath: /mounts/vpnconfig
+            readOnly: false
+      - documentIndex: *JobDocument
+        equal:
+          path: spec.template.spec.containers[0].args
+          value:
+            - |-
+              echo "Starting auto permissions job..."
+              touch /tmp/healthy
+
+              echo "Automatically correcting ownership and permissions..."
+                  echo "Automatically correcting ownership for /mounts/vpnconfig..."
+                  before=$(stat -c "%u:%g" /mounts/vpnconfig)
+                      chown  -f 568:568 /mounts/vpnconfig || echo "Failed setting ownership using chown..."
+
+                  echo "Ownership before: [$before]"
+                  echo "Ownership after: [$(stat -c "%u:%g" /mounts/vpnconfig)]"
+                  echo ""
+              echo "Finished auto permissions job..."
       - documentIndex: *DeploymentDocument
         equal:
           path: spec.template.spec.containers[0].name
@@ -401,11 +440,49 @@ tests:
               port: 8080
     asserts:
       - hasDocuments:
-          count: 2
-      - documentIndex: &DeploymentDocument 0
+          count: 3
+      - documentIndex: &JobDocument 0
+        isKind:
+          of: Job
+      - documentIndex: *JobDocument
+        equal:
+          path: metadata.name
+          value: release-name-common-test-autopermissions
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.volumes
+          content:
+            name: vpnfolder
+            hostPath:
+              path: /path/to/folder
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.containers[0].volumeMounts
+          content:
+            name: vpnfolder
+            mountPath: /mounts/vpnfolder
+            readOnly: false
+      - documentIndex: *JobDocument
+        equal:
+          path: spec.template.spec.containers[0].args
+          value:
+            - |-
+              echo "Starting auto permissions job..."
+              touch /tmp/healthy
+
+              echo "Automatically correcting ownership and permissions..."
+                  echo "Automatically correcting ownership for /mounts/vpnfolder..."
+                  before=$(stat -c "%u:%g" /mounts/vpnfolder)
+                      chown  -f 568:568 /mounts/vpnfolder || echo "Failed setting ownership using chown..."
+
+                  echo "Ownership before: [$before]"
+                  echo "Ownership after: [$(stat -c "%u:%g" /mounts/vpnfolder)]"
+                  echo ""
+              echo "Finished auto permissions job..."
+      - documentIndex: &DeploymentDocument 1
         isKind:
           of: Deployment
-      - documentIndex: &ServiceDocument 1
+      - documentIndex: &ServiceDocument 2
         isKind:
           of: Service
       - documentIndex: *DeploymentDocument
@@ -607,13 +684,52 @@ tests:
               port: 8080
     asserts:
       - hasDocuments:
-          count: 2
-      - documentIndex: &DeploymentDocument 0
+          count: 3
+      - documentIndex: &JobDocument 0
+        isKind:
+          of: Job
+      - documentIndex: &DeploymentDocument 1
         isKind:
           of: Deployment
-      - documentIndex: &ServiceDocument 1
+      - documentIndex: &ServiceDocument 2
         isKind:
           of: Service
+      - documentIndex: *JobDocument
+        equal:
+          path: metadata.name
+          value: release-name-common-test-autopermissions
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.volumes
+          content:
+            name: vpnconfig
+            hostPath:
+              path: /path/to/file
+              type: File
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.containers[0].volumeMounts
+          content:
+            name: vpnconfig
+            mountPath: /mounts/vpnconfig
+            readOnly: false
+      - documentIndex: *JobDocument
+        equal:
+          path: spec.template.spec.containers[0].args
+          value:
+            - |-
+              echo "Starting auto permissions job..."
+              touch /tmp/healthy
+
+              echo "Automatically correcting ownership and permissions..."
+                  echo "Automatically correcting ownership for /mounts/vpnconfig..."
+                  before=$(stat -c "%u:%g" /mounts/vpnconfig)
+                      chown  -f 568:568 /mounts/vpnconfig || echo "Failed setting ownership using chown..."
+
+                  echo "Ownership before: [$before]"
+                  echo "Ownership after: [$(stat -c "%u:%g" /mounts/vpnconfig)]"
+                  echo ""
+              echo "Finished auto permissions job..."
       - documentIndex: *DeploymentDocument
         equal:
           path: spec.template.spec.containers[0].name
@@ -663,13 +779,52 @@ tests:
               port: 8080
     asserts:
       - hasDocuments:
-          count: 2
-      - documentIndex: &DeploymentDocument 0
+          count: 3
+      - documentIndex: &JobDocument 0
+        isKind:
+          of: Job
+      - documentIndex: &DeploymentDocument 1
         isKind:
           of: Deployment
-      - documentIndex: &ServiceDocument 1
+      - documentIndex: &ServiceDocument 2
         isKind:
           of: Service
+      - documentIndex: *JobDocument
+        equal:
+          path: metadata.name
+          value: release-name-common-test-autopermissions
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.volumes
+          content:
+            name: vpnconfig
+            hostPath:
+              path: /path/to/file
+              type: File
+      - documentIndex: *JobDocument
+        contains:
+          path: spec.template.spec.containers[0].volumeMounts
+          content:
+            name: vpnconfig
+            mountPath: /mounts/vpnconfig
+            readOnly: false
+      - documentIndex: *JobDocument
+        equal:
+          path: spec.template.spec.containers[0].args
+          value:
+            - |-
+              echo "Starting auto permissions job..."
+              touch /tmp/healthy
+
+              echo "Automatically correcting ownership and permissions..."
+                  echo "Automatically correcting ownership for /mounts/vpnconfig..."
+                  before=$(stat -c "%u:%g" /mounts/vpnconfig)
+                      chown  -f 568:568 /mounts/vpnconfig || echo "Failed setting ownership using chown..."
+
+                  echo "Ownership before: [$before]"
+                  echo "Ownership after: [$(stat -c "%u:%g" /mounts/vpnconfig)]"
+                  echo ""
+              echo "Finished auto permissions job..."
       - documentIndex: *DeploymentDocument
         equal:
           path: spec.template.spec.containers[0].name
