better logic

diff --git a/charts/incubator/linkding/values.yaml b/charts/incubator/linkding/values.yaml
--- a/charts/incubator/linkding/values.yaml
+++ b/charts/incubator/linkding/values.yaml
@@ -41,10 +41,17 @@ lifecycle:
         - "/bin/bash"
         - "-c"
         - |
-          if [ -f /etc/linkding/data/.superuserexists ]; then
+          if [ -f /etc/linkding/data/.superuser_exists ]; then
             echo "Superuser has been created before. Skipping...";
           else
             echo "Creating superuser...";
-            python manage.py createsuperuser --username=${DJANGO_SUPERUSER_USERNAME} --email=${DJANGO_SUPERUSER_EMAIL} --noinput;
-            echo "This file is to ensure that init script won't try to create a superuser again and fail because it already exsits" > /etc/linkding/data/.superuserexists;
+            export status=99;
+            until [ $status -eq 0 ];
+            do
+              python manage.py createsuperuser --username=${DJANGO_SUPERUSER_USERNAME} --email=${DJANGO_SUPERUSER_EMAIL} --noinput;
+              status=$?;
+              sleep 3;
+            done;
+            echo "This file is to ensure that init script won't try to create a superuser again and fail because it already exsits" > /etc/linkding/data/.superuser_exists;
+            echo "Superuser Created!";
           fi;
