fix

diff --git a/charts/incubator/piwigo/values.yaml b/charts/incubator/piwigo/values.yaml
--- a/charts/incubator/piwigo/values.yaml
+++ b/charts/incubator/piwigo/values.yaml
@@ -28,6 +28,16 @@ workload:
     podSpec:
       containers:
         main:
+          lifecycle:
+            postStart:
+              type: exec
+              command:
+                - /bin/sh
+                - -c
+                - |
+                  echo "create piwigo config..."
+                  curl -X POST -d "language=${LANGUAGE}&dbhost=${DB_HOST}:3306&dbuser=${DB_USER}&dbpasswd=${DB_PASSWD}&dbname=${DB_NAME}&prefix=piwigo_&admin_name=${ADMIN_USER}&admin_pass1=${ADMIN_PASS}&admin_pass2=${ADMIN_PASS}&admin_mail=${ADMIN_EMAIL}&install=Start+installation" "http://0.0.0.0/install.php" || (echo "init config, FAILED..." && exit 1)
+                  fi
           env:
             LANGUAGE: "{{ .Values.piwigo.language }}"
             ADMIN_USER: "{{ .Values.piwigo.admin_user }}"
@@ -45,17 +55,6 @@ workload:
                 expandObjectName: false
                 name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                 key: mariadb-password
-
-lifecycle:
-  postStart:
-    exec:
-      command:
-        - /bin/sh
-        - -c
-        - |
-          echo "create piwigo config..."
-          curl -X POST -d "language=${LANGUAGE}&dbhost=${DB_HOST}:3306&dbuser=${DB_USER}&dbpasswd=${DB_PASSWD}&dbname=${DB_NAME}&prefix=piwigo_&admin_name=${ADMIN_USER}&admin_pass1=${ADMIN_PASS}&admin_pass2=${ADMIN_PASS}&admin_mail=${ADMIN_EMAIL}&install=Start+installation" "http://0.0.0.0/install.php" || (echo "init config, FAILED..." && exit 1)
-          fi
 
 persistence:
   config:
