remove variable.

diff --git a/charts/incubator/piwigo/values.yaml b/charts/incubator/piwigo/values.yaml
--- a/charts/incubator/piwigo/values.yaml
+++ b/charts/incubator/piwigo/values.yaml
@@ -35,13 +35,12 @@ workload:
                 - /bin/sh
                 - -c
                 - |
-                  post_setup="/config/POSTSETUP"
-                  if [ -f "$post_setup" ]; then
+                  if [ -f "/config/POSTSETUP" ]; then
                     echo "POSTSETUP exists, no further action is needed."
                   else
                     echo "sending api request for initial piwigo setup"
                     if curl -X POST -d "language={{ .Values.piwigo.language }}&dbhost={{ .Values.mariadb.creds.plainhost | trimAll "\"" }}:3306&dbuser={{ .Values.mariadb.mariadbUsername }}&dbpasswd={{ .Values.mariadb.creds.mariadbPassword | trimAll "\"" }}&dbname={{ .Values.mariadb.mariadbDatabase }}&prefix=piwigo_&admin_name={{ .Values.piwigo.admin_user }}&admin_pass1={{ .Values.piwigo.admin_pass }}&admin_pass2={{ .Values.piwigo.admin_pass }}&admin_mail={{ .Values.piwigo.admin_email }}&install=Start+installation" http://0.0.0.0/install.php; then
-                      touch "$post_setup" && echo "Created POSTSETUP!" || (echo "Failed to create POSTSETUP file..." && exit 1)
+                      touch "/config/POSTSETUP" && echo "Created POSTSETUP!" || (echo "Failed to create POSTSETUP file..." && exit 1)
                     else
                       echo "Failed to send api request..." && exit 1
                     fi
