feat(piwigo) configure piwigo mariadb and admin credentials (#10444)
**Description**
Configure admin credentials and mariadb sidecar
⚒️ Fixes  # <!--(issue)-->

**⚙️ Type of change**

- [X] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [X] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**
<!--
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details
for your test configuration
-->

**📃 Notes:**
<!-- Please enter any other relevant information here -->

**✔️ Checklist:**

- [X] ⚖️ My code follows the style guidelines of this project
- [X] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand
areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is
effective or that my feature works
- [X] ⬆️ I increased versions for any altered app according to semantic
versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the
following.

- [ ] 🪞 I have opened a PR on
[truecharts/containers](https://github.com/truecharts/containers) adding
the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called
`icon.png`

---

_Please don't blindly check all the boxes. Read them and only check
those that apply.
Those checkboxes are there for the reviewer to see what is this all
about and
the status of this PR with a quick glance._

diff --git a/charts/incubator/piwigo/values.yaml b/charts/incubator/piwigo/values.yaml
--- a/charts/incubator/piwigo/values.yaml
+++ b/charts/incubator/piwigo/values.yaml
@@ -17,12 +17,32 @@ service:
         targetPort: 80
         port: 10027
 
+piwigo:
+  language: en_US
+  admin_user: admin
+  admin_pass: admin123
+  admin_email: admin@email.com
+
 workload:
   main:
     podSpec:
       containers:
         main:
-          env: {}
+          lifecycle:
+            postStart:
+              type: exec
+              command:
+                - /bin/sh
+                - -c
+                - |
+                  if [ -f "/config/POSTSETUP" ]; then
+                    echo "POSTSETUP exists, no further action is needed."
+                  else
+                    while ! curl -s -o -v /dev/null http://localhost/install.php; do sleep 1; done && \
+                    curl -v -X POST -d "language={{ .Values.piwigo.language }}&dbhost={{ .Values.mariadb.creds.plainhost | trimAll "\"" }}:3306&dbuser={{ .Values.mariadb.mariadbUsername }}&dbpasswd={{ .Values.mariadb.creds.mariadbPassword | trimAll "\"" }}&dbname={{ .Values.mariadb.mariadbDatabase }}&prefix=piwigo_&admin_name={{ .Values.piwigo.admin_user }}&admin_pass1={{ .Values.piwigo.admin_pass }}&admin_pass2={{ .Values.piwigo.admin_pass }}&admin_mail={{ .Values.piwigo.admin_email }}&install=Start+installation" http://localhost/install.php && \
+                    ( touch "/config/POSTSETUP" && echo "Created POSTSETUP!") || \
+                    ( echo "Failed to create POSTSETUP file..." && exit 1 )
+                  fi
 
 persistence:
   config:
@@ -35,6 +55,11 @@ persistence:
     size: 256Gi
   varrun:
     enabled: true
+
+mariadb:
+  enabled: true
+  mariadbUsername: piwigo
+  mariadbDatabase: piwigo
 
 portal:
   open:
