fix command

diff --git a/charts/incubator/piwigo/values.yaml b/charts/incubator/piwigo/values.yaml
--- a/charts/incubator/piwigo/values.yaml
+++ b/charts/incubator/piwigo/values.yaml
@@ -51,14 +51,11 @@ workload:
           command:
             - /bin/sh
             - -c
-            - curl
-            - -X POST
-            - -d
-            - "language=${LANGUAGE}&dbhost=${DB_HOST}:3306&dbuser=${DB_USER}&dbpasswd=${DB_PASSWD}&dbname=${DB_NAME}&prefix=piwigo_&admin_name=${ADMIN_USER}&admin_pass1=${ADMIN_PASS}&admin_pass2=${ADMIN_PASS}&admin_mail=${ADMIN_EMAIL}&install=Start+installation"
-            - "http://0.0.0.0/install.php"
-      containers:
-        main:
-          env: {}
+          args:
+            - |
+              echo "init piwigo config..."
+              curl -X POST -d "language=${LANGUAGE}&dbhost=${DB_HOST}:3306&dbuser=${DB_USER}&dbpasswd=${DB_PASSWD}&dbname=${DB_NAME}&prefix=piwigo_&admin_name=${ADMIN_USER}&admin_pass1=${ADMIN_PASS}&admin_pass2=${ADMIN_PASS}&admin_mail=${ADMIN_EMAIL}&install=Start+installation" "http://0.0.0.0/install.php" || (echo "init config, FAILED..." && exit 1)
+              fi
 
 persistence:
   config:
