Update charts/incubator/qbitrr/values.yaml
Signed-off-by: Xstar97TheNoob <9399967+xstar97@users.noreply.github.com>

diff --git a/charts/incubator/qbitrr/values.yaml b/charts/incubator/qbitrr/values.yaml
--- a/charts/incubator/qbitrr/values.yaml
+++ b/charts/incubator/qbitrr/values.yaml
@@ -31,12 +31,8 @@ workload:
               if [ -f /config/config.toml ]; then
                 echo "Config file exists! Skipping..."
               else
-                if cp -n /config/config.rename_me.toml /config/config.toml; then
-                  echo "Config file copied successfully!"
-                else
-                  echo "Copying config file failed."
-                  exit 1
-                fi
+                echo "Config file is missing, getting a new one!"
+                curl -fLvo /config/config.toml https://raw.githubusercontent.com/Feramance/qBitrr/master/config.example.toml || (echo "Downloading config file, FAILED..." && exit 1)
               fi
       containers:
         main:
