Update charts/incubator/qbitrr/values.yaml
Signed-off-by: Xstar97TheNoob <9399967+xstar97@users.noreply.github.com>

diff --git a/charts/incubator/qbitrr/values.yaml b/charts/incubator/qbitrr/values.yaml
--- a/charts/incubator/qbitrr/values.yaml
+++ b/charts/incubator/qbitrr/values.yaml
@@ -16,29 +16,26 @@ service:
 workload:
   main:
     podSpec:
-      initContainers:
-        create-init-config-file:
-          enabled: true
-          type: init
-          imageSelector: "image"
-          command:
-            - /bin/sh
-            - -c
-          args:
-            - |
-              echo "Creating config.toml file..."
-              if [ -f /config/.config/config.toml ]; then
-                echo "Config file exists! Skipping..."
-              else
-                if cp -n /config/.config/config.rename_me.toml /config/.config/config.toml; then
-                  echo "Config file copied successfully!"
-                else
-                  echo "Copying config file failed."
-                  exit 1
-                fi
-              fi
       containers:
         main:
+          lifecycle:
+            postStart:
+              type: exec
+              command:
+                - /bin/sh
+                - -c
+                - |
+                  echo "Creating config.toml file..."
+                  if [ -f /config/.config/config.toml ]; then
+                    echo "Config file exists! Skipping..."
+                  else
+                    if cp -n /config/.config/config.rename_me.toml /config/.config/config.toml; then
+                      echo "Config file copied successfully!"
+                    else
+                      echo "Copying config file failed."
+                      exit 1
+                    fi
+                  fi
           probes:
             liveness:
               enabled: false
