fix secret refs and initContainer

diff --git a/charts/stable/guacamole-client/values.yaml b/charts/stable/guacamole-client/values.yaml
--- a/charts/stable/guacamole-client/values.yaml
+++ b/charts/stable/guacamole-client/values.yaml
@@ -119,63 +119,6 @@ persistence:
     enabled: true
     type: emptyDir
     mountPath: "/initdbdata"
-installContainers:
-  1-creat-initdb-file:
-    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
-    volumeMounts:
-      - name: initdbdata
-        mountPath: "/initdbdata"
-    command: ["/bin/sh", "-c"]
-    args:
-      - |-
-        echo "Creating initdb.sql file..."
-        /opt/guacamole/bin/initdb.sh --postgres >/initdbdata/initdb.sql
-        if [ -e /initdbdata/initdb.sql ]; then
-          echo "Init file created successfully!"
-          exit 0
-        else
-          echo "Init file failed to create."
-          exit 1
-        fi
-  2-initdb:
-    image: "{{ .Values.ubuntuImage.repository }}:{{ .Values.ubuntuImage.tag }}"
-    env:
-      - name: POSTGRESQL_DATABASE
-        value: "{{ .Values.cnpg.main.database }}"
-      - name: POSTGRESQL_USER
-        value: "{{ .Values.cnpg.main.user }}"
-      - name: POSTGRESQL_PORT
-        value: "5432"
-      - name: POSTGRESQL_HOSTNAME
-        valueFrom:
-          secretKeyRef:
-            name: cnpg-main-urls
-            key: plainhost
-      - name: PGPASSWORD
-        valueFrom:
-          secretKeyRef:
-            name: cnpg-main-urls
-            key: postgresql-password
-    volumeMounts:
-      - name: initdbdata
-        mountPath: "/initdbdata"
-    command: ["/bin/sh", "-c"]
-    args:
-      - |-
-        psql -h "$POSTGRESQL_HOSTNAME" -d "$POSTGRESQL_DATABASE" -U "$POSTGRESQL_USER" -p "$POSTGRESQL_PORT" -o '/dev/null' -c 'SELECT * FROM public.guacamole_user'
-        if [ $? -eq 0 ]; then
-          echo "DB already initialized. Skipping..."
-        else
-          echo "Initializing DB's schema..."
-          psql -h "$POSTGRESQL_HOSTNAME" -d "$POSTGRESQL_DATABASE" -U "$POSTGRESQL_USER" -p "$POSTGRESQL_PORT" -a -w -f /initdbdata/initdb.sql
-          if [ $? -eq 0 ]; then
-            echo "DB's schema initialized successfully!"
-            exit 0
-          else
-            echo "DB's schema failed to initialize."
-            exit 1
-          fi
-        fi
 portal:
   open:
     enabled: true
@@ -187,6 +130,54 @@ securityContext:
 workload:
   main:
     podSpec:
+      initContainers:
+        1-creat-initdb-file:
+          type: install
+          imageSelector: "image"
+          command: ["/bin/sh", "-c"]
+          args:
+            - |-
+              echo "Creating initdb.sql file..."
+              /opt/guacamole/bin/initdb.sh --postgres >/initdbdata/initdb.sql
+              if [ -e /initdbdata/initdb.sql ]; then
+                echo "Init file created successfully!"
+                exit 0
+              else
+                echo "Init file failed to create."
+                exit 1
+              fi
+        2-initdb:
+          type: install
+          imageSelector: "image"
+          env:
+            POSTGRESQL_DATABASE: "{{ .Values.cnpg.main.database }}"
+            POSTGRESQL_USER: "{{ .Values.cnpg.main.user }}"
+            POSTGRESQL_PORT: "5432"
+            POSTGRESQL_HOSTNAME:
+              secretKeyRef:
+                name: cnpg-main-urls
+                key: plainhost
+            PGPASSWORD:
+              secretKeyRef:
+                name: cnpg-main-urls
+                key: postgresql-password
+          command: ["/bin/sh", "-c"]
+          args:
+            - |-
+              psql -h "$POSTGRESQL_HOSTNAME" -d "$POSTGRESQL_DATABASE" -U "$POSTGRESQL_USER" -p "$POSTGRESQL_PORT" -o '/dev/null' -c 'SELECT * FROM public.guacamole_user'
+              if [ $? -eq 0 ]; then
+                echo "DB already initialized. Skipping..."
+              else
+                echo "Initializing DB's schema..."
+                psql -h "$POSTGRESQL_HOSTNAME" -d "$POSTGRESQL_DATABASE" -U "$POSTGRESQL_USER" -p "$POSTGRESQL_PORT" -a -w -f /initdbdata/initdb.sql
+                if [ $? -eq 0 ]; then
+                  echo "DB's schema initialized successfully!"
+                  exit 0
+                else
+                  echo "DB's schema failed to initialize."
+                  exit 1
+                fi
+              fi
       containers:
         main:
           probes:
diff --git a/charts/stable/nextcloud/values.yaml b/charts/stable/nextcloud/values.yaml
--- a/charts/stable/nextcloud/values.yaml
+++ b/charts/stable/nextcloud/values.yaml
@@ -39,27 +39,7 @@ hostAliases:
   - ip: '{{ .Values.workload.main.podSpec.containers.main.env.AccessIP | default "127.0.0.1" }}'
     hostnames:
       - "{{ if .Values.ingress.main.enabled }}{{ with (first .Values.ingress.main.hosts) }}{{ .host }}{{ end }}{{ else }}placeholder.fakedomain.dns{{ end }}"
-initContainers:
-  prestart:
-    image: "{{ .Values.alpineImage.repository }}:{{ .Values.alpineImage.tag }}"
-    securityContext:
-      runAsUser: 0
-      runAsGroup: 0
-    command:
-      - "/bin/sh"
-      - "-c"
-      - |
-        /bin/sh <<'EOF'
-        echo "Forcing permissions on userdata folder..."
-        echo "Trying to override ownship using nfs4xdr_winacl..."
-        /usr/sbin/nfs4xdr_winacl -a chown -G 33 -c '/var/www/html/data' -p '/var/www/html/data' || echo "Failed setting ownership..."
-        chmod 770 /var/www/html/data || echo "Failed to chmod..."
-        EOF
-    volumeMounts:
-      - name: data
-        mountPath: "/var/www/html/data"
-      - name: html
-        mountPath: "/var/www/html"
+
 persistence:
   html:
     enabled: true
@@ -358,6 +338,24 @@ securityContext:
 workload:
   main:
     podSpec:
+      initContainers:
+        prestart:
+          imageSelector: "image"
+          type: init
+          securityContext:
+            runAsUser: 0
+            runAsGroup: 0
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/sh <<'EOF'
+              echo "Forcing permissions on userdata folder..."
+              echo "Trying to override ownship using nfs4xdr_winacl..."
+              /usr/sbin/nfs4xdr_winacl -a chown -G 33 -c '/var/www/html/data' -p '/var/www/html/data' || echo "Failed setting ownership..."
+              chmod 770 /var/www/html/data || echo "Failed to chmod..."
+              EOF
+
       containers:
         main:
           probes:
diff --git a/charts/stable/pialert/values.yaml b/charts/stable/pialert/values.yaml
--- a/charts/stable/pialert/values.yaml
+++ b/charts/stable/pialert/values.yaml
@@ -89,35 +89,7 @@ persistence:
     noMount: true
     type: secret
     objectName: '{{ template "tc.v1.common.lib.chart.names.fullname" . }}-secret'
-initContainers:
-  init:
-    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
-    volumeMounts:
-      - name: db
-        mountPath: /home/pi/pialert/db
-      - name: config
-        mountPath: /home/pi/pialert/config
-      - name: pialert-config
-        mountPath: /tc-pialert.conf
-        subPath: pialert.conf
-    command: ["/bin/sh", "-c"]
-    args:
-      - |
-        dark_file="/home/pi/pialert/db/setting_darkmode"
-        temp_config_file="/tc-pialert.conf"
-        config_file="/home/pi/pialert/config/pialert.conf"
-        echo "Copying config file into it's directory.."
-        cp -f "$temp_config_file" "$config_file" && echo "Copied config file successfully!" || echo "Failed to copy config file..."
-        {{- if .Values.pialert.general.dark_mode }}
-        echo "Enabling dark mode file..."
-        touch "$dark_file" && echo "Created dark mode file!" || echo "Failed to create dark mode file..."
-        {{- else }}
-        if [ -f "$dark_file" ]; then
-          rm -f $dark_file && echo "Dark mode file removed!" || echo "Failed to remove dark mode file..."
-        else
-          echo "Dark mode file does not exist, no action is needed."
-        fi
-        {{- end }}
+
 portal:
   open:
     enabled: true
@@ -130,6 +102,28 @@ securityContext:
 workload:
   main:
     podSpec:
+      initContainers:
+        init:
+          imageSelector: "image"
+          type: init
+          command: ["/bin/sh", "-c"]
+          args:
+            - |
+              dark_file="/home/pi/pialert/db/setting_darkmode"
+              temp_config_file="/tc-pialert.conf"
+              config_file="/home/pi/pialert/config/pialert.conf"
+              echo "Copying config file into it's directory.."
+              cp -f "$temp_config_file" "$config_file" && echo "Copied config file successfully!" || echo "Failed to copy config file..."
+              {{- if .Values.pialert.general.dark_mode }}
+              echo "Enabling dark mode file..."
+              touch "$dark_file" && echo "Created dark mode file!" || echo "Failed to create dark mode file..."
+              {{- else }}
+              if [ -f "$dark_file" ]; then
+                rm -f $dark_file && echo "Dark mode file removed!" || echo "Failed to remove dark mode file..."
+              else
+                echo "Dark mode file does not exist, no action is needed."
+              fi
+              {{- end }}
       containers:
         main:
           env:
