update values.yaml

diff --git a/charts/incubator/plex-meta-manager/values.yaml b/charts/incubator/plex-meta-manager/values.yaml
--- a/charts/incubator/plex-meta-manager/values.yaml
+++ b/charts/incubator/plex-meta-manager/values.yaml
@@ -12,7 +12,7 @@ podSecurityContext:
   runAsGroup: 0
 
 env:
-  PMM_CONFIG: "/config/config.yaml"
+  PMM_CONFIG: "/config/config.yml"
   PMM_RUN: true
   PMM_NO_COUNTDOWN: true
 
@@ -46,11 +46,10 @@ initContainers:
     command: ["/bin/sh", "-c"]
     args:
       - |-
-        echo "Creating config.yaml file..."
+        echo "Creating config.yml file..."
         echo "current tag {{ .Values.image.tag }}"
-        if [ -e /config/config.yaml ]; then
+        if [ -e /config/config.yml ]; then
           echo "Config file exists!"
         else
-          curl -fLvo /config/config.yaml https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/config/config.yml.template
-          echo "Config file created successfully!"
+           curl -fLvo /config/config.yml https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/config/config.yml.template || ( echo "Downloading config file, FAILED..." && exit 1 )
         fi
