change initcontinaer image and adjust envs

diff --git a/charts/incubator/plex-meta-manager/values.yaml b/charts/incubator/plex-meta-manager/values.yaml
--- a/charts/incubator/plex-meta-manager/values.yaml
+++ b/charts/incubator/plex-meta-manager/values.yaml
@@ -13,6 +13,7 @@ podSecurityContext:
 
 env:
   PMM_CONFIG: "/config/config.yml"
+  # PMM_TIME: ""
   PMM_RUN: true
   PMM_NO_COUNTDOWN: true
 
@@ -39,7 +40,7 @@ persistence:
 
 initContainers:
   1-create-init-config-file:
-    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
+    image: "{{ .Values.alpineImage.repository }}:{{ .Values.alpineImage.tag }}"
     volumeMounts:
       - name: config
         mountPath: "/config"
@@ -47,9 +48,9 @@ initContainers:
     args:
       - |-
         echo "Creating config.yml file..."
-        echo "current tag {{ .Values.image.tag }}"
-        if [ -e /config/config.yml ]; then
-          echo "Config file exists!"
+        if [ -f /config/config.yml ]; then
+          echo "Config file exists!, Skipping..."
         else
-           curl -fLvo /config/config.yml https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/config/config.yml.template || ( echo "Downloading config file, FAILED..." && exit 1 )
+          echo "Config file is missing, getting a new one!"
+          curl -fLvo /config/config.yml https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/config/config.yml.template || ( echo "Downloading config file, FAILED..." && exit 1 )
         fi
