last little cleanup for the patcher

diff --git a/docs/rc2patcher b/docs/rc2patcher
--- a/docs/rc2patcher
+++ b/docs/rc2patcher
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 set -eu
-
+echo ""
+echo ""
 echo -e "\033[1mTrueCharts HotPatcher for TrueNAS SCALE RC2\033[0m"
 echo "This tool is going to patch your system to fix performance of the Apps interface..."
 echo ""
@@ -12,7 +13,7 @@ echo ""
 sleep 5
 echo "---"
 echo -e "\033[1mApplying HotPatch 2\033[0m"
-( wget -q -P /tmp https://github.com/truecharts/apps/raw/master/tools/RC2-HP2.patch && echo "download completed" || echo "download failed" ) && ( patch -N -s -p0 -d /usr/lib/python3/dist-packages/middlewared/ < /tmp/RC2-HP2.patch > /dev/null && echo "patch completed" || echo "patch failed" ) && rm -rf /tmp/RC2-HP2.patch
+( wget -q -P /tmp https://github.com/truecharts/apps/raw/master/tools/RC2-HP2.patch && echo "download completed" || echo "download failed" ) && ( patch -N -s -p0 -d /usr/lib/python3/dist-packages/middlewared/ < /tmp/RC2-HP2.patch > /dev/null && echo "patch completed" || echo "patch failed, did you install it previously already?" ) && rm -rf /tmp/RC2-HP2.patch
 
 echo "Restarting Middleware..." && systemctl restart middlewared
 sleep 10
