Add Stage-3 Apps
Please consider all these as mostly feature complete BETA Apps for the time being

Co-authored-by: Troy Prelog <35702532+tprelog@users.noreply.github.com>
Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>

diff --git a/.github/workflows/charts-release.yaml b/.github/workflows/charts-release.yaml
--- a/.github/workflows/charts-release.yaml
+++ b/.github/workflows/charts-release.yaml
@@ -37,7 +37,7 @@ jobs:
                   chartname=$(basename ${chart})
                   echo "Processing ${chart} version ${maxversion}"
                   mv ${chart}/${maxversion} ../charts/charts/${chartname}
-                  rm ../charts/charts/${chartname}/Chart.lock
+                  rm ../charts/charts/${chartname}/Chart.lock || echo "chart.lock missing for ${chartname}, continuing..."
               fi
           done
           mv library/* ../charts/charts/
