use different oci upload logic

diff --git a/.github/workflows/common.release.yaml b/.github/workflows/common.release.yaml
--- a/.github/workflows/common.release.yaml
+++ b/.github/workflows/common.release.yaml
@@ -70,7 +70,7 @@ jobs:
           filename=$(basename "$pkg")
           name="${filename%%-[0-9]*.[0-9]*.[0-9]*.tgz}"
           echo "uploading $name"
-          helm push "${pkg}" oci://quay.io/truecharts/$name || echo "failed to upload $pkg to OCI"
+          helm push "${pkg}" oci://quay.io/truecharts || echo "failed to upload $pkg to OCI"
           curl -X POST -H "Content-Type: application/json" -d '{"visibility": "public"}' -H "Authorization: Bearer ${{ secrets.QUAY_TCCR_API_TOKEN }}" "https://quay.io/api/v1/repository/tccr/$pkg/changevisibility"  || echo "failed to set $pkg to public on OCI"
         done
 
