oops

diff --git a/.github/workflows/common.release.yaml b/.github/workflows/common.release.yaml
--- a/.github/workflows/common.release.yaml
+++ b/.github/workflows/common.release.yaml
@@ -60,15 +60,15 @@ jobs:
       shell: bash
       run: echo ${{ secrets.QUAY_TCCR_TOKEN }} | helm registry login -u ${{ secrets.QUAY_TCCR_USER }} --password-stdin quay.io
 
-      - name: Push Charts to GHCR
-        run: |
-          for pkg in .cr-release-packages/*; do
-            if [ -z "${pkg:-}" ]; then
-              break
-            fi
-            helm push "${pkg}" oci://quay.io/truecharts/charts || echo "failed to upload $pkg to OCI"
-            curl -X POST -H "Content-Type: application/json" -d '{"visibility": "public"}' -H "Authorization: Bearer ${{ secrets.QUAY_TCCR_API_TOKEN }}" "https://quay.io/api/v1/repository/tccr/$pkg/changevisibility"  || echo "failed to set $pkg to public on OCI"
-          done
+    - name: Push Charts to GHCR
+      run: |
+        for pkg in .cr-release-packages/*; do
+          if [ -z "${pkg:-}" ]; then
+            break
+          fi
+          helm push "${pkg}" oci://quay.io/truecharts/charts || echo "failed to upload $pkg to OCI"
+          curl -X POST -H "Content-Type: application/json" -d '{"visibility": "public"}' -H "Authorization: Bearer ${{ secrets.QUAY_TCCR_API_TOKEN }}" "https://quay.io/api/v1/repository/tccr/$pkg/changevisibility"  || echo "failed to set $pkg to public on OCI"
+        done
 
     - name: Helm | Logout
       shell: bash
