yet another OCI fix

diff --git a/.github/workflows/common.release.yaml b/.github/workflows/common.release.yaml
--- a/.github/workflows/common.release.yaml
+++ b/.github/workflows/common.release.yaml
@@ -72,7 +72,7 @@ jobs:
           name="${filename%%-[0-9]*.[0-9]*.[0-9]*.tgz}"
           echo "uploading $name"
           helm push "${pkg}" oci://quay.io/truecharts || echo "failed to upload $pkg to OCI"
-          curl -X POST -H "Content-Type: application/json" -d '{"visibility": "public"}' -H "Authorization: Bearer ${{ secrets.QUAY_API_TOKEN }}" "https://quay.io/api/v1/repository/truecharts/$pkg/changevisibility"  || echo "failed to set $pkg to public on OCI"
+          curl -X POST -H "Content-Type: application/json" -d '{"visibility": "public"}' -H "Authorization: Bearer ${{ secrets.QUAY_TOKEN }}" "https://quay.io/api/v1/repository/truecharts/$pkg/changevisibility"  || echo "failed to set $pkg to public on OCI"
         done
 
     - name: Helm | Logout
