style: Split long lines, follow .editorconfig
Signed-off-by: Dan Christensen <opello@opello.org>

diff --git a/.github/workflows/daily.yaml b/.github/workflows/daily.yaml
--- a/.github/workflows/daily.yaml
+++ b/.github/workflows/daily.yaml
@@ -68,74 +68,96 @@ jobs:
           # Designed to ensure the appversion in Chart.yaml is in sync with the primary Chart tag if found
           # Also makes sure that home link is pointing to the correct url
           sync_tag() {
-              local chart="$1"
-              local chartname="$2"
-              local train="$3"
-              echo "Attempting to sync primary tag with appversion for: ${chartname}"
-              local tag="$(cat ${chart}/values.yaml | grep '^  tag: ' | awk -F" " '{ print $2 }' | head -1)"
-              tag="${tag%%@*}"
-              tag="${tag:-auto}"
-              tag=$(echo $tag | sed "s/release-//g")
-              tag=$(echo $tag | sed "s/release_//g")
-              tag=$(echo $tag | sed "s/version-//g")
-              tag=$(echo $tag | sed "s/version_//g")
-              tag="${tag#*V.}"
-              tag="${tag#*v-}"
-              tag="${tag#*v}"
-              tag="${tag%-*}"
-              tag="${tag:0:10}"
-              tag="${tag%-}"
-              tag="${tag%_}"
-              tag="${tag%.}"
-              echo "Updating tag of ${chartname} to ${tag}..."
-              sed -i -e "s|appVersion: .*|appVersion: \"${tag}\"|" "${chart}/Chart.yaml"
-              echo "Updating icon of ${chartname}..."
-              sed -i -e "s|icon: .*|icon: https:\/\/truecharts.org\/img\/hotlink-ok\/chart-icons\/${chartname}.png|" "${chart}/Chart.yaml"
-              echo "Updating home of ${chartname}..."
-              sed -i -e "s|home: .*|home: https:\/\/truecharts.org\/charts\/${train}\/${chartname}|" "${chart}/Chart.yaml"
-              echo "Attempting to update sources of ${chartname}..."
-              echo "Using go-yq verion: <$(go-yq -V)>"
-              # Get all sources (except truecharts)
-              curr_sources=$(go-yq '.sources[] | select(. != "https://github.com/truecharts*" and . != "https://ghcr*" and . != "docker.io*" and . != "https://docker.io*" and . != "https://hub.docker*" and . != "https://fleet.*" and . != "https://github.com/truecharts/containers/tree/master/mirror/*" and . != "https://public.ecr.aws*" and . != "https://ocir.io*" and . != "https://gcr*" and . != "https://azurecr*"  and . != "https://quay*" and . != "https://lscr*" and . != "https://github.com/truecharts/containers*" and . == "http*")' "${chart}/Chart.yaml")
-              # Empty sources list in-place
-              go-yq -i 'del(.sources.[])' "${chart}/Chart.yaml"
-              # Add truechart source
-              tcsource="https://github.com/truecharts/charts/tree/master/charts/$train/$chartname" go-yq -i '.sources += env(tcsource)' "${chart}/Chart.yaml"
-              container=$(cat website/docs/charts/description_list.md | grep "\[${chartname}\]" | cut -f3 -d '|' | grep -v 'Not Found' || echo "")
-              if [ ! -z "$container" ]; then
-                prefix="https://hub.docker.com/"
-                container=${container#https://}
-                if echo ${container} | grep 'tccr'; then
+            local chart="$1"
+            local chartname="$2"
+            local train="$3"
+            echo "Attempting to sync primary tag with appversion for: ${chartname}"
+            local tag="$(cat ${chart}/values.yaml | grep '^  tag: ' | awk -F" " '{ print $2 }' | head -1)"
+            tag="${tag%%@*}"
+            tag="${tag:-auto}"
+            tag=$(echo $tag | sed "s/release-//g")
+            tag=$(echo $tag | sed "s/release_//g")
+            tag=$(echo $tag | sed "s/version-//g")
+            tag=$(echo $tag | sed "s/version_//g")
+            tag="${tag#*V.}"
+            tag="${tag#*v-}"
+            tag="${tag#*v}"
+            tag="${tag%-*}"
+            tag="${tag:0:10}"
+            tag="${tag%-}"
+            tag="${tag%_}"
+            tag="${tag%.}"
+            echo "Updating tag of ${chartname} to ${tag}..."
+            sed -i -e "s|appVersion: .*|appVersion: \"${tag}\"|" "${chart}/Chart.yaml"
+            echo "Updating icon of ${chartname}..."
+            sed -i -e "s|icon: .*|icon: https:\/\/truecharts.org\/img\/hotlink-ok\/chart-icons\/${chartname}.png|" "${chart}/Chart.yaml"
+            echo "Updating home of ${chartname}..."
+            sed -i -e "s|home: .*|home: https:\/\/truecharts.org\/charts\/${train}\/${chartname}|" "${chart}/Chart.yaml"
+            echo "Attempting to update sources of ${chartname}..."
+            echo "Using go-yq verion: <$(go-yq -V)>"
+            # Get all sources (except truecharts)
+            curr_sources=$(
+              go-yq '
+                .sources[] |
+                select(
+                  . != "https://github.com/truecharts*" and
+                  . != "https://ghcr*" and
+                  . != "docker.io*" and
+                  . != "https://docker.io*" and
+                  . != "https://hub.docker*" and
+                  . != "https://fleet.*" and
+                  . != "https://github.com/truecharts/containers/tree/master/mirror/*" and
+                  . != "https://public.ecr.aws*" and
+                  . != "https://ocir.io*" and
+                  . != "https://gcr*" and
+                  . != "https://azurecr*" and
+                  . != "https://quay*" and
+                  . != "https://lscr*" and
+                  . != "https://github.com/truecharts/containers*" and
+                  . == "http*"
+                )
+                ' \
+              "${chart}/Chart.yaml"
+            )
+            # Empty sources list in-place
+            go-yq -i 'del(.sources.[])' "${chart}/Chart.yaml"
+            # Add truechart source
+            tcsource="https://github.com/truecharts/charts/tree/master/charts/$train/$chartname" go-yq -i '.sources += env(tcsource)' "${chart}/Chart.yaml"
+            container=$(cat website/docs/charts/description_list.md | grep "\[${chartname}\]" | cut -f3 -d '|' | grep -v 'Not Found' || echo "")
+            if [ ! -z "$container" ]; then
+              prefix="https://hub.docker.com/"
+              container=${container#https://}
+              if echo ${container} | grep 'tccr'; then
                 container=${container#tccr.io}
                 container="https://github.com/truecharts/containers/tree/master/mirror"
                 prefix=""
-                elif echo ${container} | grep 'lscr'; then
+              elif echo ${container} | grep 'lscr'; then
                 container="https://fleet.linuxserver.io/"
                 prefix=""
-                elif echo ${container} | grep 'gcr'; then
+              elif echo ${container} | grep 'gcr'; then
                 prefix="https://"
-                elif echo ${container} | grep 'azurecr'; then
+              elif echo ${container} | grep 'azurecr'; then
                 prefix="https://"
-                elif echo ${container} | grep 'public.ecr.aws'; then
+              elif echo ${container} | grep 'public.ecr.aws'; then
                 prefix="https://"
-                elif echo ${container} | grep 'ocir.io'; then
+              elif echo ${container} | grep 'ocir.io'; then
                 prefix="https://"
-                elif echo ${container} | grep 'hub.docker'; then
+              elif echo ${container} | grep 'hub.docker'; then
                 prefix="https://"
-                elif echo ${container} | grep 'docker.io'; then
+              elif echo ${container} | grep 'docker.io'; then
                 container=${container#docker.io}
                 prefix="https://hub.docker.com"
-                elif echo ${container} | grep 'hub.docker'; then
+              elif echo ${container} | grep 'hub.docker'; then
                 prefix="https://"
-                fi
-                container="${prefix}${container}" go-yq -i '.sources += env(container) | .sources |= unique' "${chart}/Chart.yaml"
               fi
-              # Add the rest of the sources
-              while IFS= read -r line; do
-                src="$line" go-yq -i '.sources += env(src)' "${chart}/Chart.yaml" || echo "src set error"
-              done <<< "$curr_sources"
-              echo "Sources of ${chartname} updated!"
-              }
+              container="${prefix}${container}" go-yq -i '.sources += env(container) | .sources |= unique' "${chart}/Chart.yaml"
+            fi
+            # Add the rest of the sources
+            while IFS= read -r line; do
+              src="$line" go-yq -i '.sources += env(src)' "${chart}/Chart.yaml" || echo "src set error"
+            done <<< "$curr_sources"
+            echo "Sources of ${chartname} updated!"
+          }
           export -f sync_tag
 
           for train in enterprise stable incubator dependency; do
