Update daily.yaml
Signed-off-by: Kjeld Schouten <kjeld@schouten-lebbing.nl>

diff --git a/.github/workflows/daily.yaml b/.github/workflows/daily.yaml
--- a/.github/workflows/daily.yaml
+++ b/.github/workflows/daily.yaml
@@ -200,7 +200,7 @@ jobs:
             echo "Correcting Chart.yaml for Train: ${train}..."
             for chart in $(ls "charts/${train}"); do
               echo "Correcting Chart.yaml for Chart: ${chart}..."
-              sync_tag "charts/${train}/${chart}" "${chart}" "${train}"
+              sync_tag "charts/${train}/${chart}" "${chart}" "${train}" || echo "failed"
             done
           done
 
