Fix some mistakes

diff --git a/.github/workflows/housekeeping.yaml b/.github/workflows/housekeeping.yaml
--- a/.github/workflows/housekeeping.yaml
+++ b/.github/workflows/housekeeping.yaml
@@ -108,7 +108,7 @@ jobs:
               --chart-search-root="/home/runner/work/apps/apps/charts/library/common"
           helm-docs \
               --ignore-file=".helmdocsignore" \
-              --output-file="/home/runner/work/apps/apps/docs/apps/common/helm-values.md" \
+              --output-file="helm-values.md" \
               --template-files="/home/runner/work/apps/apps/templates/docs/common-helm-values.md.gotmpl" \
               --chart-search-root="/home/runner/work/apps/apps/charts/library/common"
 
@@ -183,7 +183,8 @@ jobs:
                   sed -i '1s/^/# License<br>\n\n/' docs/apps/${train}/${chartname}/LICENSE.md || echo "license edit failed, continuing..."
               fi
             done
-          yes | cp -rf /home/runner/work/apps/apps/docs/apps/common/README.md  docs/apps/common/index.md || echo "common readme copy failed, continuing..."
+          mkdir -p docs/apps/common || echo "app path already exists, continuing..."
+          yes | cp -rf charts/library/common/README.md  docs/apps/common/index.md || echo "common readme copy failed, continuing..."
           echo "Processed charts for ${train}:"
           ls docs/apps/${train}/ || echo "no Apps in train"
           done
@@ -191,6 +192,7 @@ jobs:
       - name: Cleanup
         run: |
           rm -rf changes.json
+          rm -rf /home/runner/work/apps/apps/charts/library/common/helm-values.md
 
       - name: Commit and Push Housekeeping
         run: |
