Change CI license reformating

diff --git a/.github/workflows/wiki-create-docs.yaml b/.github/workflows/wiki-create-docs.yaml
--- a/.github/workflows/wiki-create-docs.yaml
+++ b/.github/workflows/wiki-create-docs.yaml
@@ -49,7 +49,7 @@ jobs:
           cp .github/CODE_OF_CONDUCT ../wiki/content/code_of_conduct.md || echo "CODE_OF_CONDUCT copy failed, continuing..."
           cp .github/CONTRIBUTING ../wiki/content/development/contributing.md || echo "CONTRIBUTING copy failed, continuing..."
           cp LICENSE ../wiki/content/LICENSE.md || echo "license copy failed, continuing..."
-          sed -i '1s/^/#License\n/' ../wiki/content/LICENSE.md
+          sed -i '1s/^/# License<br>\n\n/' ../wiki/content/LICENSE.md
           ls ../wiki/content/
           cd ..
 
@@ -68,7 +68,7 @@ jobs:
                 fi
                 cp ${chart}/${maxfolderversion}/README.md ../wiki/content/apps/${chartname}/index.md || echo "readme copy failed, continuing..."
                 cp ${chart}/${maxfolderversion}/LICENSE ../wiki/content/apps/${chartname}/LICENSE.md || echo "license copy failed, continuing..."
-                sed -i '1s/^/#License\n/' ../wiki/content/apps/${chartname}/LICENSE.md || echo "license edit failed, continuing..."
+                sed -i '1s/^/# License<br>\n\n/' ../wiki/content/apps/${chartname}/LICENSE.md || echo "license edit failed, continuing..."
             fi
           done
           ls ../wiki/content/apps/
