Docs rework fase 2 (#182)
* move faq to seperate file

* Slight tweaking and adding license file(s) to wiki

* Update README.md

* Port git guide from UnityStation

* Rename Ingress to Reverse Proxy

Fixes #183

* Prefer central templates

* Add initial information about Storage

* Port Chart structure info from TrueNAS/charts readme

* Create and document standardised Chart.yaml layout

* update tautulli version

* Add custom liveness probes for sonarr, radarr, lidarr and readarr

* Add Maintainers Wanted page

* Update existing Chart.yaml files

diff --git a/.github/workflows/wiki-create-docs.yaml b/.github/workflows/wiki-create-docs.yaml
--- a/.github/workflows/wiki-create-docs.yaml
+++ b/.github/workflows/wiki-create-docs.yaml
@@ -44,15 +44,12 @@ jobs:
       - name: Create general wiki
         run: |
           cd master
-          for doc in .github/docs/*; do
-              if [ -d "${doc}" ]; then
-                  docname=$(basename ${doc})
-                  cp -Rf ${doc} ../wiki/content/
-              fi
-          done
+          cp -Rf .github/docs/* ../wiki/content/
           cp .github/README.md ../wiki/content/index.md || echo "readme copy failed, continuing..."
           cp .github/CODE_OF_CONDUCT ../wiki/content/code_of_conduct.md || echo "CODE_OF_CONDUCT copy failed, continuing..."
           cp .github/CONTRIBUTING ../wiki/content/development/contributing.md || echo "CONTRIBUTING copy failed, continuing..."
+          cp .github/LICENSE ../wiki/content/development/LICENSE.md || echo "license copy failed, continuing..."
+          sed -i '1s/^/#License\n/' ../wiki/content/LICENSE.md
           ls ../wiki/content/
           cd ..
 
@@ -70,6 +67,8 @@ jobs:
                   cp -f ${chart}/${maxfolderversion}/docs/* ../wiki/content/apps/${chartname}/
                 fi
                 cp ${chart}/${maxfolderversion}/README.md ../wiki/content/apps/${chartname}/index.md || echo "readme copy failed, continuing..."
+                cp ${chart}/${maxfolderversion}/LICENSE ../wiki/content/apps/${chartname}/LICENSE.md || echo "license copy failed, continuing..."
+                sed -i '1s/^/#License\n/' ../wiki/content/apps/${chartname}/LICENSE.md
             fi
           done
           ls ../wiki/content/apps/
